version: "3"
services:
  nginx:
    build: ./nginx
    restart: always
    ports:
      - "8080:80"
    logging:
      options:
        max-size: 100m
  
  flask:
    build: ./backend
    restart: always
    ports:
      - "5000:5000"
    logging:
      options:
        max-size: 100m