version: "3"
services:
  nginx:
    build: ./nginx
    restart: always
    ports:
      - "127.0.0.1:50080:80"
    logging:
      options:
        max-size: 100m
  
  flask:
    build: ./backend
    restart: always
    ports:
      - "127.0.0.1:50081:5000"
    logging:
      options:
        max-size: 100m